### ISSUE TITLE
MCP23S18 just doesn't work.

### ISSUE THREAD

**Issue by Coder-256** [sumotoy/gpio_expander#2]
If the title doesn't already explain it, the MCP23S18 interface just doesn't work. I think I found the issue, though. Mainly the problem is that it actually doesn't support HAEN. This library appears to be just a slightly modified version of the MCP28S1**7** library. However, I only found two differences - the pins are in different orders and that the A0, A1, and A2 pins are replaced by NC pins. The address will always be 000, so 0x20 should always work as the address.
![Difference between MCP23S17 and MCP23S18 control byte format](http://i.snag.gy/jgcwM.jpg)
Anyways, even using `mcp23s18 mcp(GPIO_PIN, 0x20);`, I still can't access any of the pins. By the way, in the datasheet the pins are labelled as `GPA0...7` and `GPB0...7`, but in your library, they're accessed as numbers. If you could define constants for each pin, that would also make it a lot less confusing. One last thing - there are both "A" and "B" registers for the chip. Son instead of there being one `GPIO` register, there is a `GPIOA` and a `GPIOB` register. All of this info can be found on the [datasheet](http://ww1.microchip.com/downloads/en/DeviceDoc/22103a.pdf).

**Comment by sumotoy** [comment]
MCP23S18 it's a open collector so when test it you need a resistor on output or it will never work.
Apart that, you right, it doesn't support HAEN so has fixed address, it's a simple task to fix and will do really soon, this week I will release a new library with each family separated.Recently I've decided to split the library in different families, my attemp to create an universal library it's possible but not easy because chip differencies, btw I will maintain the same commands so it will be easy to switch chip.
About your request, datasheet on hand, the two chip have the same port numbering scheme, using macro to identify pins (that actually are 1 or 2 port of 8 bit) it's not a great idea, you will break some operation that use whole port , think about an user that renumber pins as he like.
There's cases where you need to use port dinamically as input/output (check the key matrix example) and this it's possible to do fast only wnen manipulating the whole port.
Actually I don't think the port numbering it's so complicated, 0...15, 8 per side.
The new library can use port expansion so it will take care of multiple chip seen as one.
I have a MCP23S18 here, I check it this night.

**Comment by sumotoy** [comment]
Really thanks for report this, please check the new version and let me know,

**Comment by Coder-256** [comment]
Thanks, but two things:

1. The readme hasn't been updated (remove HAEN from the features column).
2. Whenever I try to call `gpioDigitalRead()`, I get 2 to the power of whatever pin I specified. For example, with no pins connected, here is my code:

```c++
#include <SPI.h>
#include <mcp23s18.h>

#define GPIO_PIN    12

mcp23s18 mcp(GPIO_PIN);
int state;

void setup() {
  // put your setup code here, to run once:
  Serial.begin(9600);
  mcp.begin();
  mcp.gpioPinMode(INPUT);
  Serial.println("Starting...");
}

void loop() {
  // put your main code here, to run repeatedly:
  //while (!finished);
  for (int i=1; i<=16; i++) {
    state = mcp.gpioDigitalRead(i);
    Serial.println("State for pin " + String(i) + ": " + String(state));
    delay(1000);
  }
}
```

And the output:


> Starting...
> State for pin 1: 2
> State for pin 2: 4
> State for pin 3: 8
> State for pin 4: 16
> State for pin 5: 32
> State for pin 6: 64
> State for pin 7: 128
> State for pin 8: 256
> State for pin 9: 512
> State for pin 10: 1024
> State for pin 11: 2048
> State for pin 12: 4096
> State for pin 13: 8192
> State for pin 14: 16384
> State for pin 15: -32768
> State for pin 16: 0
> ...

**Comment by sumotoy** [comment]
Interesting, just to test, can you run this program?



void printPort()
{
	int i;
	uint16_t port = readGpioPort();
  for (i=15; i>=0; i--){
    if (bitRead(port,i)==1){
      Serial.print("1");
    } 
    else {
      Serial.print("0");
    }
  }
  Serial.print("\n");
}

**Comment by Coder-256** [comment]
It always returns `1111111111111111`, no matter if I connect any of the pins to ground or 5v.

**Comment by sumotoy** [comment]
I have checked the registers and are correct.
Did you put on each input a pullup resistor?
try add after mcp.gpioPinMode(INPUT);<br>
mcp.portPullup(HIGH);
